services:
  magic-platform:
    env_file:
      - .env.dev
    build:
      context: ./mage
    command: /app/run_app.sh mage start $PROJECT_NAME
    ports:
      - "6789:6789"
    volumes:
      # Mount your local codebase to the container.
      - ./mage:/$MAGE_CODE_PATH
      # Store the data output on local machine to easily debug (optional).
      - ~/.mage_data:/$MAGE_CODE_PATH/mage_data
    restart: on-failure:5
    networks:
      - app-network
    depends_on:
      - magic-database
      - elasticsearch
    stdin_open: true # used for interactive debugging
    tty: true # used for interactive debugging

  magic-database:
    image: pgvector/pgvector:0.6.0-pg16
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - ~/.postgres/data:/var/lib/postgresql/data
      # Custom database initialization scripts (optional).
      - ./mage/scripts/database:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - app-network


  grafana:
    # image: my-custom-grafana
    build:
      context: ./grafana
    # container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage4:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    depends_on:
      - magic-database
    networks:
      - app-network

  ifab_chatbot_app:
    image: ifab_chatbot_app
    build:
      context: ./ifab_chatbot_app
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: $OPENAI_API_KEY
      POSTGRES_HOST: magic-database
    ports:
      - "8501:8501"
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage4: {}
  elasticsearch-data:
    driver: local