{
 "title": "IFAB_RAG_MONITORING_1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total query counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \r\ncount(*)  over(order by insert_ts rows between unbounded preceding and current row ) cnt,\r\ninsert_ts\r\nfrom ifab_rag.qna;"
    }
   ]
  },
  {
   "title": "Negativefeedback counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \r\ncount(*)  over(order by insert_ts rows between unbounded preceding and current row ) cnt,\r\ninsert_ts\r\nfrom  ifab_rag.feedbacks where feedback ;"
    }
   ]
  },
  {
   "title": "Feedback chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*), case when feedback then 'positive' else 'negative' end as feedback from ifab_rag.feedbacks\r\ngroup by feedback;"
    }
   ]
  },
  {
   "title": "Positive feedback ratio",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select \r\nround(cast(count(case when feedback then 1 end) \r\n\tover(order by insert_ts rows between unbounded preceding and current row ) as numeric (5,3)) /\r\ncount(*) \r\n\tover(order by insert_ts rows between unbounded preceding and current row ) , 2) cnt,\r\ninsert_ts,\r\nfeedback\r\nfrom  ifab_rag.feedbacks ;"
    }
   ]
  },
  {
   "title": "Positive feedback counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select \r\ncount(*)  over(order by insert_ts rows between unbounded preceding and current row ) cnt,\r\ninsert_ts\r\nfrom  ifab_rag.feedbacks where feedback ;"
    }
   ]
  }
 ]
}